### ISSUE TITLE
tfvars files are ignored

### ISSUE THREAD

**Issue by eugenetaranov** [nhurel/terraspec#13]
Hello,

I am trying to run terraspec (assuming terraform version v0.12.21) and seems like it is ignoring *.tfvars files with variables defined:

```
/root/terraspec-linux-x64 --spec /mnt/ --claim-version=v0.12.21                                                                                                                                                                  
🏷  mnt
Unassigned variable : The input variable "environment" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.

🏁 1 suites run in 21.4598379s 	error : 1 	success : 0
Terraform version 0.13.5 substitued with provided one 0.12.21
```

**Comment by nhurel** [comment]
Hello,
can you give more details about your directory structure ?
terraspec is supposed to be run from the same directory as terraform (where your .tf files are). tfvars files are picked from the same directory as your terraspec ones.

**Comment by eugenetaranov** [comment]
hi @nhurel , yes exactly, that's how it is structured:
```
╰─❯ ls                                                                                                                                                                                                                               
main.tf  test.tfvars  variables.tf
```

**Comment by nhurel** [comment]
Your test.tfvars should be in the same directory as your ".tfspec" file. You can have a look at this example here for example : https://github.com/nhurel/terraspec/tree/master/examples/aws/module_ec2 

As you can write multiple test scenario for a given terraform config, terraspec will load tfspec and tfvars file that are located in the same directory. So you can test your config with different input variables.

**Comment by eugenetaranov** [comment]
Thanks @nhurel , it worked!
