### ISSUE TITLE
Terraform v0.14.x

### ISSUE THREAD

**Issue by yitsushi** [nhurel/terraspec#14]
Right now terraspec is using v0.13.5. We tried to update it to v0.14.6 (or any other 0.14.x versions) and we gave up because I couldn't even call `go get ./...` because go is crying about checksum mismatch. Later I discovered the same happens on the upstream hashicorp/terraform repository as well.

I don't know what can be the solution or how to approach it, I'm opening this issue to take a public note about it (if others have the same problem). We may try to do it later, but now we are just pinning all terraform to v0.13.5.

**Comment by yitsushi** [comment]
Calling `go get ./...` from my local machine on the upstream terraform codebase:
```
terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ git remote -v
origin  git@github.com:hashicorp/terraform (fetch)
origin  git@github.com:hashicorp/terraform (push)

terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ git status --porcelain

terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ go get ./...
verifying github.com/hashicorp/go-getter@v1.5.1: checksum mismatch
        downloaded: h1:LZ49OxqBBtdKJymlpX7oTyqGBQRg4xxQDyPW4hzoZqM=
        go.sum:     h1:lM9sM02nvEApQGFgkXxWbhfqtyN+AyhQmi+MaMdBDOI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by nhurel** [comment]
Hello,
I've just pushed a branch tf0.14 I can build locally with `go build` with go 1.14 and go1.15.

Hope this helps

**Comment by wyardley** [comment]
>  I've just pushed a branch tf0.14 I can build locally with go build with go 1.14 and go1.15.

Will a version of terraspec with tf 0.14.x be released soon?
```
% terraspec --version       
Terraspec Version : 0.7.16
Terraform Version : 0.13.5
```
