### ISSUE TITLE
Terraspec is crashing with SIGSEGV error

### ISSUE THREAD

**Issue by michael-yudin** [nhurel/terraspec#18]
Hello,

I want to check that a resource that is not covered in **main.tf** will be created., but Terraspec is crashing with SIGSEGV error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ae9aa7]goroutine 51 [running]:
github.com/nhurel/terraspec/lib.laxSchema(0x0, 0xc001770970)
        /root/source/lib/spec.go:551 +0x37
github.com/nhurel/terraspec/lib.decodeBody(0x25261c0, 0xc0029ef340, 0xc001770970, 0xd, 0xc000229340, 0xc003e6b340, 0x0, 0x0, 0x0, 0x0, ...)
        /root/source/lib/spec.go:489 +0x13e
github.com/nhurel/terraspec/lib.ParseSpec(0xc000158000, 0x1292, 0x1492, 0xc0004ef800, 0x1b, 0xc000229340, 0x0, 0x0, 0x0, 0x0)
        /root/source/lib/spec.go:426 +0x470
github.com/nhurel/terraspec/lib.ReadSpec(0xc0004ef800, 0x1b, 0xc000229340, 0xc00052fd00, 0x1, 0x1, 0x0)
        /root/source/lib/spec.go:361 +0x1cc
main.PrepareTestSuite(0x202de65, 0x1, 0xc0002a4930, 0xc0004c1d80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/source/main.go:209 +0x40b
main.runTestCase(0xc0002a4930, 0xc0004c1d80, 0x0, 0xc0005ba300)
        /root/source/main.go:137 +0x6a
main.execTerraspec.func1(0xc0004c1d80, 0x0, 0xc0005ba300, 0xc0004cb170, 0xc0002a4930)
        /root/source/main.go:95 +0x48
created by main.execTerraspec
        /root/source/main.go:94 +0x1dd
```
There is example of code spec/default/default.tfspec
```
assert "random_string" "some_password" {
      length      = 16
      lower       = true
      min_lower   = 0
      min_numeric = 0
      min_special = 0
      min_upper   = 0
      number      = true
      special     = false
      upper       = true
}
```

**Comment by nhurel** [comment]
Hello
Could you give me more info ? You say the resource is not in your main.tf, so is it supposed to be in a module you call ?
Also can you tell me which version of terraform and terraspec you use ?

**Comment by nhurel** [comment]
I think I've reproduced a pushed a fix. Terraspec won't crash anymore but exit with an error message.
Still I don't understand your use case :thinking:

**Comment by tataranovich** [comment]
Imagine that during terraform module refactoring some resource definition was removed from the Terraform configuration. Tests were not updated accordingly and terraspec start crashing (SIGSEGV) instead of reporting missing resource in plan. So my expectation that such case should end as failed test instead of application crash.

**Comment by nhurel** [comment]
The issue raised here, as I understand / reproduce it is :
- terraform code doesn't have any resource using the `random` provider nor declare this provider as required in terraform config
- terraspec scenario tries to make assertion on a `random_string` resource.

This was crashing. I've pushed a fix to end the execution with an error message instead.
Terraspec don't manage any plugin (ie. provider) installation itself, and relies on what's been installed by `terraform init`, hence this behavior.

Regarding your comment @tataranovich, if you have a resource that's been removed from your configuration but still referenced by your specs, terraspec will raise a proper "assertion error", among the other assertion results.
For example, a terraform config that used to create 3 aws resources that only creates 2 after a refactoring, then terraspec will return an error message stating that the resource could not be found if you still have an assertion on it.

**Comment by tataranovich** [comment]
I tested your fix and it looks good to me. Now we get error about missing provider if provider is not specified in Terraform configuration and missing resource if provider specified but resource was not declared. I think we are good to close this issue.
