### ISSUE TITLE
Newest version of AWS Provider issue causes rpc error

### ISSUE THREAD

**Issue by chenrog** [nhurel/terraspec#19]
main.tfspec:
```
assert "aws_ssm_parameter" "eks_kubernetes_image_ssm" {
  name      = "/my/ssm/parameter"
  type      = "String"
  value     = "null"
}
```

This main.tf works fine:
```
terraform {
  required_version = ">= 0.13.0, < 0.14.0"

  required_providers {
    aws = "~> 2.0"
  }
}

resource "aws_ssm_parameter" "eks_kubernetes_image_ssm" {
  name      = "/my/ssm/parameter"
  type      = "String"
  value     = "null"
}
```

This main.tf fails:
```
terraform {
  required_version = ">= 0.13.0, < 0.14.0"

  required_providers {
    aws = "~> 3.0"
  }
}

resource "aws_ssm_parameter" "eks_kubernetes_image_ssm" {
  name      = "/my/ssm/parameter"
  type      = "String"
  value     = "null"
}
```

Failure:
` rpc error: code = Unavailable desc = transport is closing :  `

**Comment by nhurel** [comment]
Indeed I can reproduce this, but haven't found the cause so far.
As the error happens in the provider plugin, it gets complicated to debug but I'm still investigating to find a fix.

**Comment by nhurel** [comment]
After digging in aws provider and terraform-plugin-sdk v2, I finally found that aws provider v3 can't work if it hasn't been properly configured first.

Until now, terraspec never run the plugin configuration phase as that's when the provider will check it can authenticate against the cloud provider and I wanted to have the possibility to run terraspec even without valid credentials.
In version 3, aws provider added more configuration in its provider (like default_tags), hence the necessity for the provider to be properly configured, even if all calls to the cloud provider are mocked.

To keep the possibility to test aws configurations, I've added a command line flag (`--configure-provider`) that will make terraspec execute the configuration phase of the provider. 

This means that, for a terraform config using aws provder v3, you need :
- to run terraspec with `--confiure-provider` flag
- to have valid aws credentials configured for the provider (either in your provider block or via the environment variables)
