### ISSUE TITLE
Mocking module variables

### ISSUE THREAD

**Issue by omegion** [nhurel/terraspec#20]
Hi!

It seems we do not have support for module variables:

```
Unassigned variable : The input variable "account_id" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.
```

Is there any plan to add this feature @nhurel?

**Comment by nhurel** [comment]
Hello,

Could  you give me more info about your test case ?
The input variables should be set via a tfvars file located next to your tfspec file. This should be enough for all situations but I may miss something in what you try to achieve ?

**Comment by omegion** [comment]
@nhurel thanks for your suggestion. It just did work. I missed this feature from the documentation. Maybe we can add another example for using `tfvars`.
