### ISSUE TITLE
Feature Request: Add the ability to stub out modules

### ISSUE THREAD

**Issue by tomelliot16** [nhurel/terraspec#22]
Modules have variables and outputs which theoretically can be mocked/stubbed out. This feature would promote units when working with modules because every resource in the module can be tested in explicit spec tests in the module and not at the level of the terraform that is using the module. Not sure there is support yet to do this but I couldn't find anything.
something like
```
assert_module "module_name" {
  some_variable_name = "some_variable_value"
  return {
    some_output_name = "some_output_value"
  }
}
```

**Comment by nhurel** [comment]
This is not possible to mock module outputs. However I don't understand what you mean by :
> every resource in the module can be tested in explicit spec tests in the module and not at the level of the terraform that is using the module.

You can write assertions for resources created  by a module called by your terraform code. The assert must then be written like 
```
assert "module.<module_name>.<resource_type>" "<resource_name> "{
}
```

You can see examples in the `examples/aws/module_ec2` folder.
This is not mentioned in the README though, i'll add documentation for that.

Does it fit your needs ?
