### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by Silvere112** [nhurel/terraspec#24]
Hello,

I'm currently using the tool for local development (thanks).
Now I'm integrating the testing into my CI/CD workflow. For that, I built an image that contains terraspec and terraform.

Are you interested in adding the corresponding Dockerfile to this repository?

**Comment by nhurel** [comment]
Hello,
Thanks for your feedback. 

I'm glad to hear you're using it in your CI/CD as well.

Thanks for your proposal but I don't think it's useful to add the Dockerfile here. Even if it definitely makes sense for you to build an image with terraform and terraspec together I don't think it's worth providing a Dockerfile for this in this repository.
People may use different version of terraform than you or may want to package other tools as well, so I prefer to let everyone build the image that best fit their needs.
