### ISSUE TITLE
terraform.workspace variable does not seem supported

### ISSUE THREAD

**Issue by tomelliot16** [nhurel/terraspec#3]
terraform workpace is used to create multiple of the same tf stack. The variable terraform.workspace is is used to create unique names for resources to not collide. When terraspecing the tf code it fails with a null pointer exception. My guess is that this is just piping that has not been added yet.

**Comment by tomelliot16** [comment]
@nhurel I might try and add this support myself maybe a
```
terraform_mock {
   workspace = "my-very-special-workspace"
}
```

**Comment by nhurel** [comment]
To be honest I don't use terraform workspace myself, so haven't looked into it but i'm definitely happy if you can submit a PR to provide this support. :+1:

**Comment by tomelliot16** [comment]
To keep the domain language correct after looking under the hood I'm changing it to
```
mock_metadata {
  workspace = "lol"
}
```

Glad to help, just testing what you have now gets me really excited to use it more.

**Comment by tomelliot16** [comment]
Looks like this is supported now closing this
